"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
from dotenv import load_dotenv
load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-fallback-key-change-this')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# Parse ALLOWED_HOSTS from environment variable
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# File Upload Settings - Allow large chapter files (up to 500MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 524288000  # 500 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 524288000  # 500 MB  
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000  # Increase field limit


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    
    # Local apps
    'manga',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mangatk',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}



# Database configuration from environment variable
# import dj_database_url
# DATABASES = {
#     'default': dj_database_url.config(
#         default=os.getenv('DATABASE_URL'),
#         conn_max_age=600
#     )
# }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS Configuration
# Parse CORS origins from environment variable
cors_origins = os.getenv('CORS_ALLOWED_ORIGINS', 'http://localhost:3000,http://127.0.0.1:3000')
CORS_ALLOWED_ORIGINS = [origin.strip() for origin in cors_origins.split(',')]

CORS_ALLOW_CREDENTIALS = True

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,  # 20 items per page for better performance
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'manga.auth0_utils.Auth0JSONWebTokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'UNICODE_JSON': True,
    'COMPACT_JSON': False,
}

# JWT Configuration
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Cache Configuration - Required for async upload progress tracking
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 3600,  # 1 hour
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    }
}

# ImgBB API Configuration
IMGBB_API_KEY = os.getenv('IMGBB_API_KEY')
IMGBB_API_URL = 'https://api.imgbb.com/1/upload'

# Add Auth0 variables at the bottom
AUTH0_DOMAIN = os.getenv('AUTH0_DOMAIN', os.getenv('YOUR_AUTH0_DOMAIN')) # Get from Auth0 Dashboard
AUTH0_AUDIENCE = os.getenv('AUTH0_AUDIENCE', os.getenv('YOUR_AUTH0_API_IDENTIFIER', 'https://mangatk')) # Get from Auth0 Dashboard


# backend/config/settings.py

AUTH_USER_MODEL = 'manga.User'

CORS_ALLOW_ALL_ORIGINS = True
ALLOWED_HOSTS = ['*']


# ==================== AI Translation Pipeline ====================
# Set model source: HuggingFace ID (e.g. 'username/model-name') or local path.
# Local paths in weights/ directory take priority if they exist.
AI_TRANSLATION_PIPELINE = {
    # Translation model (Seq2Seq) — HuggingFace ID or local path
    'TRANSLATION_MODEL': os.getenv('AI_TRANSLATION_MODEL', 'Bart2277/JPtoAR_transaltion_model_for_comics'),

    # Sentiment model (BERT) — HuggingFace ID or local path
    'SENTIMENT_MODEL': os.getenv('AI_SENTIMENT_MODEL', 'Bart2277/sentment_analysis_model_for_comics'),

    # YOLO bubble detector — HuggingFace repo ID or local .pt file path
    'BUBBLE_DETECTOR_MODEL': os.getenv('AI_BUBBLE_DETECTOR_MODEL', 'Bart2277/comic-detector'),

    # Source/target language
    'SOURCE_LANG': os.getenv('AI_SOURCE_LANG', 'ja'),
    'TARGET_LANG': os.getenv('AI_TARGET_LANG', 'ar'),
}

# Modal.com GPU endpoint (leave empty to use local pipeline)
# After deploying modal_app.py, paste the endpoint URL here:
# Example: 'https://YOUR_USER--mangatk-translation-translate.modal.run'
MODAL_ENDPOINT_URL = os.getenv('MODAL_ENDPOINT_URL', '')
