# Generated by Django 5.2.4 on 2025-12-10 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['category', 'requirement_value']},
        ),
        migrations.AddField(
            model_name='achievement',
            name='is_secret',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievement',
            name='rarity',
            field=models.CharField(choices=[('common', 'عادي'), ('rare', 'نادر'), ('epic', 'ملحمي'), ('legendary', 'أسطوري')], default='common', max_length=20),
        ),
        migrations.AddField(
            model_name='achievement',
            name='slug',
            field=models.SlugField(default=0, help_text='Unique ID like read_1, time_1h', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='achievement',
            name='category',
            field=models.CharField(choices=[('reading', 'القراءة'), ('time', 'الوقت'), ('collection', 'المجموعة'), ('social', 'التواصل'), ('secret', 'سري')], max_length=50),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='name_ar',
            field=models.CharField(default='', help_text='Arabic name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='achievement',
            name='requirement_type',
            field=models.CharField(help_text='Type: chapters_read, time_spent, etc', max_length=50),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='requirement_value',
            field=models.IntegerField(help_text='Threshold value to unlock'),
        ),
    ]
