# Generated by Django 5.2.4 on 2025-12-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_alter_achievement_options_achievement_is_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='publish_date',
            field=models.DateField(blank=True, help_text='تاريخ نشر أول فصل', null=True),
        ),
    ]
