# Generated by Django 5.2.4 on 2025-12-13 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0003_manga_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='target_manga',
            field=models.ForeignKey(blank=True, help_text='If set, this achievement is for completing/reading this specific manga', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='manga.manga'),
        ),
    ]
