# Generated by Django 5.2.4 on 2025-12-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0004_achievement_target_manga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=100, help_text='Currency for translations and rewards'),
        ),
    ]
