# Generated by Django 5.2.4 on 2025-12-15 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0006_mangaview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['price']},
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(blank=True, help_text='وصف الخطة'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='نسبة الخصم (0-100)', max_digits=5),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='duration_type',
            field=models.CharField(choices=[('monthly', 'شهري'), ('yearly', 'سنوي')], default='monthly', help_text='نوع المدة', max_length=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='ميزات إضافية كقائمة نصوص'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_active',
            field=models.BooleanField(default=True, help_text='هل الخطة مفعلة؟'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='ads_enabled',
            field=models.BooleanField(default=True, help_text='هل الإعلانات مفعلة؟'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='monthly_free_translations',
            field=models.PositiveIntegerField(default=0, help_text='عدد الترجمات المجانية شهرياً'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(help_text='اسم الخطة', max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='point_multiplier',
            field=models.FloatField(default=1.0, help_text='مضاعف النقاط (1.0, 1.5, 2.0)'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='سعر الاشتراك', max_digits=8),
        ),
    ]
