# Generated by Django 5.2.4 on 2025-12-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0007_alter_subscriptionplan_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration_type',
            field=models.CharField(choices=[('monthly', 'شهري'), ('yearly', 'سنوي'), ('lifetime', 'لا محدود')], default='monthly', help_text='نوع المدة', max_length=10),
        ),
    ]
