# Generated by Django 5.2.4 on 2025-12-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0008_add_lifetime_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='يظهر في البنر الرئيسي'),
        ),
    ]
