# Generated by Django 5.2.4 on 2025-12-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0009_add_is_featured_to_manga'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='equipped_title',
            field=models.CharField(blank=True, help_text='اللقب المجهز من الإنجازات', max_length=100),
        ),
    ]
