# Generated by Django 5.2.4 on 2025-12-17 12:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0010_add_equipped_title_to_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITranslationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='اسم النموذج', max_length=200)),
                ('api_endpoint', models.URLField(help_text='رابط API للنموذج', max_length=500)),
                ('api_key', models.CharField(blank=True, help_text='مفتاح API (اختياري)', max_length=500)),
                ('extra_headers', models.JSONField(blank=True, default=dict, help_text='Headers إضافية')),
                ('request_template', models.JSONField(blank=True, default=dict, help_text='قالب الطلب JSON')),
                ('response_path', models.CharField(default='translated_image', help_text='مسار الصورة في الرد (مثل: data.image)', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='النموذج الافتراضي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Translation Model',
                'verbose_name_plural': 'AI Translation Models',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranslationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('uploading', 'جاري الرفع'), ('extracting', 'جاري فك الضغط'), ('translating', 'جاري الترجمة'), ('completed', 'مكتمل'), ('failed', 'فشل'), ('pending_publish', 'في انتظار النشر')], default='uploading', max_length=20)),
                ('temp_upload_path', models.CharField(blank=True, max_length=500)),
                ('temp_extracted_path', models.CharField(blank=True, max_length=500)),
                ('translation_results', models.JSONField(blank=True, default=list)),
                ('chapter_number', models.FloatField(blank=True, null=True)),
                ('chapter_title', models.CharField(blank=True, max_length=500)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('total_pages', models.IntegerField(default=0)),
                ('translated_pages', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ai_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manga.aitranslationmodel')),
                ('target_manga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translated_chapters', to='manga.manga')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Translation Job',
                'verbose_name_plural': 'Translation Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
