# Generated by Django 5.2.4 on 2025-12-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0011_aitranslationmodel_translationjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translationjob',
            name='chapter_number',
        ),
        migrations.RemoveField(
            model_name='translationjob',
            name='chapter_title',
        ),
        migrations.RemoveField(
            model_name='translationjob',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='translationjob',
            name='target_manga',
        ),
        migrations.AddField(
            model_name='translationjob',
            name='output_file_path',
            field=models.CharField(blank=True, help_text='مسار ملف CBZ المترجم', max_length=500),
        ),
        migrations.AlterField(
            model_name='translationjob',
            name='status',
            field=models.CharField(choices=[('uploading', 'جاري الرفع'), ('extracting', 'جاري فك الضغط'), ('translating', 'جاري الترجمة'), ('creating_cbz', 'جاري إنشاء الملف'), ('completed', 'مكتمل'), ('failed', 'فشل')], default='uploading', max_length=20),
        ),
    ]
