# Generated by Django 5.2.4 on 2025-12-27 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0012_remove_translationjob_chapter_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationjob',
            name='original_images_paths',
            field=models.JSONField(blank=True, default=list, help_text='مسارات الصور الأصلية المؤقتة'),
        ),
    ]
