# Generated by Django 5.2.4 on 2025-12-29 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0013_translationjob_original_images_paths'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='total_images_count',
            field=models.IntegerField(default=0, help_text='إجمالي عدد الصور'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='upload_status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('uploading', 'جاري الرفع'), ('completed', 'مكتمل'), ('failed', 'فشل')], default='completed', help_text='حالة رفع الصور', max_length=20),
        ),
        migrations.AddField(
            model_name='chapter',
            name='uploaded_images_count',
            field=models.IntegerField(default=0, help_text='عدد الصور المرفوعة'),
        ),
        migrations.CreateModel(
            name='FcmToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
