# Generated by Django 5.2.4 on 2026-03-04 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0014_chapter_total_images_count_chapter_upload_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='active_from',
            field=models.DateTimeField(blank=True, help_text='If set, the achievement can only be earned after this date/time', null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='active_until',
            field=models.DateTimeField(blank=True, help_text='If set, the achievement can only be earned before this date/time', null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='target_category',
            field=models.ForeignKey(blank=True, help_text='If set, this achievement is for reading mangas in this specific category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='manga.category'),
        ),
        migrations.AddField(
            model_name='user',
            name='equipped_achievement',
            field=models.ForeignKey(blank=True, help_text='الإنجاز المجهز ليظهر فوق صورة الحساب', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_by_users', to='manga.achievement'),
        ),
    ]
