# Generated by Django 5.2.4 on 2026-03-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0015_achievement_active_from_achievement_active_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='story_type',
            field=models.CharField(choices=[('manga', 'Manga'), ('manhwa', 'Manhwa'), ('manhua', 'Manhua'), ('comic', 'Comic')], default='manhwa', max_length=20),
        ),
    ]
