# Generated by Django 5.2.4 on 2026-03-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0016_manga_story_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='artist',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
