# Generated by Django 5.2.4 on 2026-03-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0017_manga_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgBBUploadStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, help_text='تاريخ الرفع', unique=True)),
                ('count', models.PositiveIntegerField(default=0, help_text='عدد الصور المرفوعة في هذا اليوم')),
            ],
            options={
                'verbose_name': 'ImgBB Upload Stat',
                'verbose_name_plural': 'ImgBB Upload Stats',
                'ordering': ['-date'],
            },
        ),
    ]
