# Generated by Django 5.2.4 on 2026-03-21 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0018_imgbbuploadstats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='reference_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, help_text='The Frontend URL to redirect to when clicked', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('points', 'Points / Economy'), ('translation', 'Translation Complete'), ('upload', 'Upload Complete'), ('chapter', 'New Chapter Released')], default='points', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(help_text='The user receiving this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
