# Generated by Django 5.2.4 on 2026-03-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0019_remove_notification_reference_id_notification_link_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('points', 'Points / Economy'), ('translation', 'Translation Complete'), ('upload', 'Upload Complete'), ('chapter', 'New Chapter Released')], default='points', max_length=20),
        ),
    ]
