# Generated by Django 5.2.4 on 2026-04-06 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0020_alter_notification_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='name_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Arabic Name'),
        ),
    ]
