# Generated by Django 5.2.4 on 2026-04-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0021_genre_name_ar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, db_index=True, max_length=150),
        ),
    ]
